// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crqpanvfnjytpcdbqmox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNycXBhbnZmbmp5dHBjZGJxbW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDg1MDIsImV4cCI6MjA3MTE4NDUwMn0.mXXakWETRL50jruw4Uouh25fznyJChT2cOJCVLLLAkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});